### ISSUE TITLE
Posting fails with "InvalidRequestContent"

### ISSUE THREAD

**Issue by desombre** [bbeesley/gha-notify-teams-on-release#2]
I used the basic example setup:
```
name: notify-teams-on-release
on:
  release:
    types: [published]
concurrency: '1'
jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: bbeesley/gha-notify-teams-on-release@main
        with:
          webhook-link:  ${{ secrets.TEAMS_WEBHOOK_URL }}
```
This is the output of the github actions logs:
```
  if [ "Test title" != '' ]; then
    curl -X POST "***" \
    --data '{"@context":"https://schema.org/extensions","@type":"MessageCard","themeColor":"d9534f","title":"Release Test title created on repository copresence/demo-repository","text":"test body 
  - [x] check
  
  
  > quote
  
  `formatted_code`
  
  foo bar"}'
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   426  100   183  100   243    287    381 --:--:-- --:--:-- --:--:--   668
{"error":{"code":"InvalidRequestContent","message":"The input body for trigger 'manual' of type 'Request' must be of type JSON, but was of type 'application/x-www-form-urlencoded'."}}
```
